server:
  port: 8081

spring:

  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    show-sql: true
    database: POSTGRESQL