version: "3.7"
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: local_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=backend
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: