server:
  port: 8080

spring:

  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:2345/jwt-demo
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
        hibernate.format_sql: true
    generate-ddl: true
    show-sql: true

    database: POSTGRESQL